#!/bin/bash
. /etc/battery-charge-levels
BATTERY_START_CHARGE_LEVEL=$[ ${BATTERY_STOP_CHARGE_LEVEL} - 4 ];
sudo tpacpi-bat -s ST 1 ${BATTERY_START_CHARGE_LEVEL}
sudo tpacpi-bat -s SP 1 ${BATTERY_STOP_CHARGE_LEVEL}
