#!/bin/bash
. /etc/battery-charge-levels
max_bat=`/usr/bin/acpi | wc -l`
for i in `seq 1 $max_bat` ; do
	sudo tpacpi-bat -s ST ${i} ${BATTERY_START_CHARGE_LEVEL}
	sudo tpacpi-bat -s SP ${i} ${BATTERY_STOP_CHARGE_LEVEL}
done
