#!/bin/bash
max_bat=`/usr/bin/acpi | wc -l`
for i in `seq 1 $max_bat` ; do
        echo "battery $i:"
	echo "start charging at $(sudo tpacpi-bat -g ST ${i})";
	echo "stop charging at $(sudo tpacpi-bat -g SP ${i})";
done
